version: "3.8"
services:
  sso:
    image: bitnami/keycloak:20
    restart: always
    ports:
      - "10000:8080"
    volumes:
      - ./keycloak:/tmp/export/
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_DATABASE_VENDOR=dev-mem
      - KEYCLOAK_EXTRA_ARGS="-Dkeycloak.import=/tmp/export/keycloak-export.json"