spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: helloService
          uri: http://localhost:8081
          predicates:
            - Path=/hello-api/**
          filters:
            - name: StripPrefix
              args:
                parts: 1
        - id: greetingService
          uri: http://localhost:8082
          predicates:
            - Path=/greeting-api/**
          filters:
            - name: StripPrefix
              args:
                parts: 1

management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

springdoc:
  swagger-ui:
    urls:
      - url: http://localhost:8080/hello-api/v3/api-docs
        display-name: Hello
        name: hello
      - url: http://localhost:8080/greeting-api/v3/api-docs
        display-name: Greeting
        name: greeting