spring:
  application:
    name: api-gateway
  session:
    redis:
      save-mode: always
      namespace: 'spring:session'
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: api-gateway
            client-secret: R3uGbQ7oIxmVCBIREfdZ5DCXNXY6SFIE
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: openid
        provider:
          my-provider:
            issuer-uri: http://localhost:9990/auth/realms/api-gateway
  cloud:
    gateway:
      routes:
        - id: helloServiceSwaggerConfig
          uri: http://localhost:8081
          predicates:
            - Path=/hello-service/**
          filters:
            - name: TokenRelay
            - name: StripPrefix
              args:
                parts: 1
        - id: helloService
          uri: http://localhost:8081
          predicates:
            - Path=/hello/**
          filters:
            - name: HelloSession
            - name: LocalResponseCache
            - name: TokenRelay
#            - name: CircuitBreaker
#              args:
#                name: "exampleSlowCircuitBreaker"
#                fallbackUri: "forward:/fallback/account"
#            - name: TokenRelay
        - id: greetingServiceSwaggerConfig
          uri: http://localhost:8082
          predicates:
            - Path=/greeting-service/**
          filters:
            - name: TokenRelay
            - name: StripPrefix
              args:
                parts: 1
        - id: greetingService
          uri: http://localhost:8082
          predicates:
            - Path=/greeting/**

server:
  reactive:
    session:
      cookie:
        name: SESSION-${spring.application.name}
        max-age: 1800
        secure: true

management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

gateway:
  terms:
    - id: apiService
      path: "/new"
    - id: noop
      path: "/greeting"
  security:
    - id: apiService
      path: "/old"
    - id: noop
      path: "/greeting"

springdoc:
  swagger-ui:
    urls:
      - url: http://localhost:8080/hello-service/v3/api-docs
        display-name: Hello
        name: heello
      - url: http://localhost:8080/greeting-service/v3/api-docs
        display-name: Greeting
        name: greeting