spring:
  application:
    name: api-gateway
  session:
    redis:
      save-mode: always
      namespace: 'spring:session'
    timeout: 10000
  cloud:
    gateway:
      routes:
        - id: tracerService
          uri: ${TRACER_SERVICE_HOST}
          predicates:
            - Path=/**
          filters:
            - name: HelloSession
            - name: SaveSession
#            - name: CircuitBreaker
#              args:
#                name: "exampleSlowCircuitBreaker"
#                fallbackUri: "forward:/fallback/account"
#            - name: RedirectFilter
#              args:
#                redirectLocation: "http://localhost:8080/public/hello.html"
#            - name: TokenRelay

server:
  reactive:
    session:
      cookie:
        name: SESSION-${spring.application.name}
        max-age: 1800
        secure: true

management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


