spring:
  application:
    name: api
  session:
    redis:
      flush-mode: on_save
      namespace: 'spring:session'

server:
  port: 8082

management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'




