spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: api-gateway
          client-secret: 5751392f-23a5-41db-ad8b-360afa5b3dbe
          introspection-uri: "${IDP_DOMAIN:http://localhost:10000}/realms/api-gateway/protocol/openid-connect/token/introspect"
