server:
  port: 8081

spring:
  application:
    name: web-tracing
  session:
    redis:
      flush-mode: on_save
      namespace: 'spring:session'

management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
